#!/bin/sh

echo " "
echo "//-----------------------------//"
echo "Running formatter for Rust code"
echo "//-----------------------------//"
echo " "
cargo fmt
git add -A
echo "\033[0;32mFormatting done...\033[0m"
echo " "
echo "//-----------------------------//"
echo "Running CARGO test suite"
echo "//-----------------------------//"
echo " "
cargo test

if [ $? -ne 0 ]; then
    echo " "
    echo "\033[0;31m//-----------------------------//\033[0m"
    echo "\033[0;31mCARGO tests failed, aborting commit.\033[0m"
    echo "\033[0;31m//-----------------------------//\033[0m"
    echo " "
    exit 1
fi

echo "//-----------------------------//"